# Use official Python image
FROM python:3.11-slim


# Set working directory inside container
WORKDIR /app


# Copy dependency file
COPY requirements.docker.txt .


# Install Python dependencies
RUN pip install --no-cache-dir --timeout=1000 -r requirements.docker.txt


# Copy project files
COPY . .


# Streamlit default port
EXPOSE 8501


# Start Streamlit application
CMD ["streamlit", "run", "frontend_app.py", "--server.address=0.0.0.0", "--server.port=8501"]