# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app


# Copy dependency file
COPY requirements.docker.txt .


# Install Python dependencies
RUN pip install --no-cache-dir --timeout=1000 -r requirements.docker.txt


# Copy project files
COPY . .


# Expose FastAPI port
EXPOSE 8000


# Start FastAPI server
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]